Update README.md, removing "chat on gitter" badge
Auto-DL/Generator pull request #26
Opened 2020-10-12 08:08 UTC by NathanPang001

Removed "chat on gitter" badge from Readme, pretty sure this is how you wanted it, tell me if you want it differently and I can change it.

2020-10-12 10:23 UTC, ADI10HERO requested changes
Hey please link it to the issue and  prefix the title with [Fixes #25]

2020-10-12 16:33 UTC, NathanPang001 commented
Sorry about that, ill fix it.

2020-10-14 10:26 UTC, ADI10HERO approved these changes

2020-10-14 10:26 UTC, ADI10HERO commented
Thanks for the PR
Enjoy your hacktober :) 

Cheers,
Adi

2020-11-08 11:07 UTC, merged