Added slack icon, removed Gitter icon
Auto-DL/Generator pull request #30
Opened 2020-10-16 20:08 UTC by dumbcheese

Issue #29 fix

2020-10-16 20:13 UTC, ADI10HERO requested changes
Hey, the issue is #28 

Rest everything is okay :)

Please make these edits, thanks for contributing, enjoy your hacktober :)

2020-10-17 08:51 UTC, dumbcheese commented
Pardon, fixes #28

2020-10-17 20:46 UTC, ADI10HERO approved these changes

2020-11-08 11:11 UTC, ADI10HERO commented
Hey thanks for the PR, closing it as the issue was already solved by another PR :)

2020-11-08 11:11 UTC, closed without merging